const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('launcher', {
  getTikTokState: () => ipcRenderer.invoke('tiktok:get'),
  connectTikTok: username => ipcRenderer.invoke('tiktok:connect', username),
  disconnectTikTok: () => ipcRenderer.invoke('tiktok:disconnect'),
  onTikTokState: callback => { const listener = (_, state) => callback(state); ipcRenderer.on('tiktok:state', listener); return () => ipcRenderer.removeListener('tiktok:state', listener); },
  getSelfUpdate: () => ipcRenderer.invoke('self-update:get'),
  checkSelfUpdate: () => ipcRenderer.invoke('self-update:check'),
  downloadSelfUpdate: () => ipcRenderer.invoke('self-update:download'),
  installSelfUpdate: () => ipcRenderer.invoke('self-update:install'),
  onSelfUpdate: callback => { const listener = (_event, state) => callback(state); ipcRenderer.on('self-update:state', listener); return () => ipcRenderer.removeListener('self-update:state', listener); },
  getCatalog: () => ipcRenderer.invoke('catalog:get'),
  getCachedApps: () => ipcRenderer.invoke('apps:cached'),
  getApps: () => ipcRenderer.invoke('apps:list'),
  setSession: (accessToken,options) => ipcRenderer.invoke('auth:set-session', accessToken,options),
  onSessionBlocked: callback => {const listener=(_,reason)=>callback(reason);ipcRenderer.on('auth:blocked',listener);return()=>ipcRenderer.removeListener('auth:blocked',listener);},
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setAutoUpdate: enabled => ipcRenderer.invoke('settings:auto-update', Boolean(enabled)),
  setAutoStart: enabled => ipcRenderer.invoke('settings:auto-start', Boolean(enabled)),
  redeemPromo: code => ipcRenderer.invoke('promo:redeem', code),
  getSubscription: () => ipcRenderer.invoke('subscription:get'),
  getSubscriptionQuote: months => ipcRenderer.invoke('subscription:quote', Number(months)),
  createSubscriptionOrder: months => ipcRenderer.invoke('subscription:create-order', Number(months)),
  verifySubscriptionOrder: orderId => ipcRenderer.invoke('subscription:verify-order', orderId),
  cancelSubscriptionOrder: orderId => ipcRenderer.invoke('subscription:cancel-order', orderId),
  openExternal: target => ipcRenderer.invoke('external:open', target),
  getStatuses: () => ipcRenderer.invoke('apps:status'),
  onAppRunning: callback => { const listener = (_, value) => callback(value); ipcRenderer.on('app:running', listener); return () => ipcRenderer.removeListener('app:running', listener); },
  getAppStatus: item => ipcRenderer.invoke('app:status', item),
  install: (id, item) => ipcRenderer.invoke('app:install', { id, item }),
  update: (id, item) => ipcRenderer.invoke('app:update', { id, item }),
  launch: (id, item) => ipcRenderer.invoke('app:launch', { id, item }),
  close: (id, item) => ipcRenderer.invoke('app:close', { id, item }),
  uninstall: (id, item) => ipcRenderer.invoke('app:uninstall', { id, item }),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  closeLauncher: () => ipcRenderer.invoke('window:close'),
  onProgress: callback => ipcRenderer.on('download:progress', (_event, value) => callback(value))
  ,onUninstallProgress: callback => ipcRenderer.on('uninstall:progress', (_event, value) => callback(value))
});
